export const rows = [
  {
    id: 1,
    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "user",
  },
  {
    id: 2,
    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "admin",
  },
  {
    id: 3,
    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "manager",
  },
  {
    id: 4,
    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "admin",
  },
  {
    id: 5,
    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "user",
  },
  {
    id: 6,
    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "manager",
  },
  {
    id: 7,
    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "user",
  },
  {
    id: 8,
    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "manager",
  },
  {
    id: 9,
    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "user",
  },
  {
    id: 10,
    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "user",
  },
];
