export const rows = [
  {
    id: 1,
    registerid: "54545",
    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "user",
    address: "644hjhj -street",
    city: "Newyourk",
    zipcode: "478",
  },
  {
    id: 2,
    registerid: "54545",
    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "admin",
    address: "644hjhj -street",
    city: "Newyourk",
    zipcode: "478",
  },
  {
    id: 3,
    registerid: "54545",

    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "manager",
    address: "644hjhj -street",
    city: "Newyourk",
    zipcode: "478",
  },
  {
    id: 4,
    registerid: "54545",

    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "admin",
    address: "644hjhj -street",
    city: "Newyourk",
    zipcode: "478",
  },
  {
    id: 5,
    registerid: "54545",

    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "user",
    address: "644hjhj -street",
    city: "Newyourk",
    zipcode: "478",
  },
  {
    id: 6,
    registerid: "54545",

    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "manager",
    address: "644hjhj -street",
    city: "Newyourk",
    zipcode: "478",
  },
  {
    id: 7,
    registerid: "54545",

    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "user",
    address: "644hjhj -street",
    city: "Newyourk",
    zipcode: "478",
  },
  {
    id: 8,
    registerid: "54545",
    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "manager",
    address: "644hjhj -street",
    city: "Newyourk",
    zipcode: "478",
  },
  {
    id: 9,
    registerid: "54545",
    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "user",
    address: "644hjhj -street",
    city: "Newyourk",
    zipcode: "478",
  },
  {
    id: 10,
    registerid: "54545",

    name: "mostafa",
    email: "mostafa@gmail.com",
    age: "33",
    phone: "0mostafa002602mostafa30",
    access: "user",
    address: "644hjhj -street",
    city: "Newyourk",
    zipcode: "478",
  },
];
